const fs = require("fs");
const path = require("path");
const emojis = require("../data/emojis");
const prefabs = require("../data/prefabs");
const positions = require("../data/positions");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src");

const emojiByAlias = Object.fromEntries(emojis.map((entry) => [entry.alias, entry.emoji]));
const positionById = Object.fromEntries(positions.map((entry) => [entry.id, entry]));

function writeFile(name, contents) {
  fs.writeFileSync(path.join(SRC, name), contents, "utf8");
}

function quote(value) {
  return JSON.stringify(value);
}

function validatePrefab(prefab) {
  if (!emojiByAlias[prefab.base]) {
    throw new Error(`Unknown base alias "${prefab.base}" in prefab "${prefab.name}"`);
  }

  if (!emojiByAlias[prefab.overlay]) {
    throw new Error(`Unknown overlay alias "${prefab.overlay}" in prefab "${prefab.name}"`);
  }

  if (!positionById[prefab.position]) {
    throw new Error(`Unknown position "${prefab.position}" in prefab "${prefab.name}"`);
  }
}

function toCatalog(prefab) {
  const position = positionById[prefab.position];
  return {
    ...prefab,
    baseEmoji: emojiByAlias[prefab.base],
    overlayEmoji: emojiByAlias[prefab.overlay],
    x: typeof prefab.x === "number" ? prefab.x : position.x,
    y: typeof prefab.y === "number" ? prefab.y : position.y,
    positionLabel: position.label
  };
}

function formatEm(value) {
  const normalized = Number(value).toFixed(2).replace(/\.?0+$/, "");
  return `${normalized}em`;
}

function generatePrefabCatalog(list) {
  const catalog = list.map(toCatalog);
  return `/* This file is generated by scripts/generate-prefabs.js */
(function (global) {
  const prefabs = ${JSON.stringify(catalog, null, 2)};
  global.EmojiStackPrefabs = prefabs;

  if (global.EmojiStack) {
    global.EmojiStack.prefabs = prefabs;
  }
})(window);
`;
}

function generatePrefabs() {
  prefabs.forEach(validatePrefab);
  const catalog = prefabs.map(toCatalog);
  const css = ["/* This file is generated by scripts/generate-prefabs.js */"];
  const pairSelectors = catalog.map((prefab) => `[class~=${quote(`${prefab.baseEmoji}${prefab.overlayEmoji}`)}]`);

  css.push(pairSelectors.join(",\n") + " {");
  css.push('  --es-base: "";');
  css.push('  --es-sub: "";');
  css.push("  --es-x: 0em;");
  css.push("  --es-y: 0em;");
  css.push("  --es-sub-size: 0.56;");
  css.push("  --es-rotate: 0deg;");
  css.push("  --es-opacity: 1;");
  css.push("  --es-base-shadow: none;");
  css.push("  --es-overlay-shadow: 0 0 0.08em rgb(0 0 0 / 0.28);");
  css.push("  --es-overlay-filter: none;");
  css.push("  --es-shift-z: 0;");
  css.push("  display: inline-block;");
  css.push("  position: relative;");
  css.push("  width: 1em;");
  css.push("  height: 1em;");
  css.push("  line-height: 1;");
  css.push("  vertical-align: -0.12em;");
  css.push("  font-style: normal;");
  css.push("  font-weight: 400;");
  css.push("  font-variant-ligatures: none;");
  css.push("  isolation: isolate;");
  css.push("}");

  css.push(pairSelectors.map((selector) => `${selector}::before,\n${selector}::after`).join(",\n") + " {");
  css.push("  position: absolute;");
  css.push("  inset: 0;");
  css.push("  display: grid;");
  css.push("  place-items: center;");
  css.push("  line-height: 1;");
  css.push("  pointer-events: none;");
  css.push("  user-select: none;");
  css.push("}");

  css.push(pairSelectors.map((selector) => `${selector}::before`).join(",\n") + " {");
  css.push("  content: var(--es-base);");
  css.push("  text-shadow: var(--es-base-shadow);");
  css.push("}");

  css.push(pairSelectors.map((selector) => `${selector}::after`).join(",\n") + " {");
  css.push("  content: var(--es-sub);");
  css.push("  inset: auto;");
  css.push("  left: 50%;");
  css.push("  top: 50%;");
  css.push("  width: 1em;");
  css.push("  height: 1em;");
  css.push("  font-size: calc(1em * var(--es-sub-size));");
  css.push("  opacity: var(--es-opacity);");
  css.push("  text-shadow: var(--es-overlay-shadow);");
  css.push("  filter: var(--es-overlay-filter);");
  css.push("  transform: translate(calc(-50% + var(--es-x)), calc(-50% + var(--es-y))) rotate(var(--es-rotate)) translateZ(var(--es-shift-z));");
  css.push("  transform-origin: center;");
  css.push("}");

  for (const prefab of catalog) {
    css.push(`.p-${prefab.name} {`);
    css.push(`  --es-base: ${quote(prefab.baseEmoji)};`);
    css.push(`  --es-sub: ${quote(prefab.overlayEmoji)};`);
    css.push(`  --es-x: ${formatEm(prefab.x)};`);
    css.push(`  --es-y: ${formatEm(prefab.y)};`);
    css.push(`  --es-sub-size: ${prefab.subSize};`);
    css.push(`  --es-opacity: ${prefab.opacity || 1};`);
    css.push(`  --es-rotate: ${prefab.rotate || "0deg"};`);
    css.push("}");

    css.push(`[class~=${quote(`${prefab.baseEmoji}${prefab.overlayEmoji}`)}] {`);
    css.push(`  --es-base: ${quote(prefab.baseEmoji)};`);
    css.push(`  --es-sub: ${quote(prefab.overlayEmoji)};`);
    css.push(`  --es-x: ${formatEm(prefab.x)};`);
    css.push(`  --es-y: ${formatEm(prefab.y)};`);
    css.push(`  --es-sub-size: ${prefab.subSize};`);
    css.push(`  --es-opacity: ${prefab.opacity || 1};`);
    css.push(`  --es-rotate: ${prefab.rotate || "0deg"};`);
    css.push("}");
  }

  writeFile("prefabs.css", `${css.join("\n")}\n`);
  writeFile("prefabs.generated.js", generatePrefabCatalog(prefabs));
  return prefabs;
}

if (require.main === module) {
  generatePrefabs();
}

module.exports = generatePrefabs;
