const fs = require("fs");
const path = require("path");
const emojis = require("../data/emojis");
const prefabs = require("../data/prefabs");
const positions = require("../data/positions");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src");

const emojiByAlias = Object.fromEntries(emojis.map((entry) => [entry.alias, entry.emoji]));
const positionById = Object.fromEntries(positions.map((entry) => [entry.id, entry]));

function writeFile(name, contents) {
  fs.writeFileSync(path.join(SRC, name), contents, "utf8");
}

function quote(value) {
  return JSON.stringify(value);
}

function validatePrefab(prefab) {
  if (!emojiByAlias[prefab.base]) {
    throw new Error(`Unknown base alias "${prefab.base}" in prefab "${prefab.name}"`);
  }

  if (!emojiByAlias[prefab.overlay]) {
    throw new Error(`Unknown overlay alias "${prefab.overlay}" in prefab "${prefab.name}"`);
  }

  if (!positionById[prefab.position]) {
    throw new Error(`Unknown position "${prefab.position}" in prefab "${prefab.name}"`);
  }
}

function toCatalog(prefab) {
  const position = positionById[prefab.position];
  return {
    ...prefab,
    baseEmoji: emojiByAlias[prefab.base],
    overlayEmoji: emojiByAlias[prefab.overlay],
    x: typeof prefab.x === "number" ? prefab.x : position.x,
    y: typeof prefab.y === "number" ? prefab.y : position.y,
    positionLabel: position.label
  };
}

function formatEm(value) {
  const normalized = Number(value).toFixed(2).replace(/\.?0+$/, "");
  return `${normalized}em`;
}

function generatePrefabCatalog(list) {
  const catalog = list.map(toCatalog);
  return `/* This file is generated by scripts/generate-prefabs.js */
(function (global) {
  const prefabs = ${JSON.stringify(catalog, null, 2)};
  global.EmojiStackPrefabs = prefabs;

  if (global.EmojiStack) {
    global.EmojiStack.prefabs = prefabs;
  }
})(window);
`;
}

function generatePrefabs() {
  prefabs.forEach(validatePrefab);
  const catalog = prefabs.map(toCatalog);
  const css = ["/* This file is generated by scripts/generate-prefabs.js */"];

  for (const prefab of catalog) {
    css.push(`.p-${prefab.name} {`);
    css.push(`  --es-base: ${quote(prefab.baseEmoji)};`);
    css.push(`  --es-sub: ${quote(prefab.overlayEmoji)};`);
    css.push(`  --es-x: ${formatEm(prefab.x)};`);
    css.push(`  --es-y: ${formatEm(prefab.y)};`);
    css.push(`  --es-sub-size: ${prefab.subSize};`);
    css.push(`  --es-opacity: ${prefab.opacity || 1};`);
    css.push(`  --es-rotate: ${prefab.rotate || "0deg"};`);
    css.push("}");
  }

  writeFile("prefabs.css", `${css.join("\n")}\n`);
  writeFile("prefabs.generated.js", generatePrefabCatalog(prefabs));
  return prefabs;
}

if (require.main === module) {
  generatePrefabs();
}

module.exports = generatePrefabs;
