const fs = require("fs");
const path = require("path");
const emojis = require("../data/emojis");
const positions = require("../data/positions");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src");

function writeFile(name, contents) {
  fs.writeFileSync(path.join(SRC, name), contents, "utf8");
}

function cssVar(emoji) {
  return JSON.stringify(emoji);
}

function generateEmojiCss(list) {
  const lines = [
    "/* This file is generated by scripts/generate-emojis.js */"
  ];

  for (const entry of list) {
    lines.push(`.${entry.emoji} { --es-token: ${cssVar(entry.emoji)}; }`);
  }

  return `${lines.join("\n")}\n`;
}

function generateAliasCss(list) {
  const lines = [
    "/* This file is generated by scripts/generate-emojis.js */"
  ];

  for (const entry of list) {
    lines.push(`.e-${entry.alias} { --es-token: ${cssVar(entry.emoji)}; }`);
  }

  return `${lines.join("\n")}\n`;
}

function generateRegistry(list) {
  const aliasToEmoji = {};
  const literalToEmoji = {};

  for (const entry of list) {
    aliasToEmoji[`e-${entry.alias}`] = entry.emoji;
    literalToEmoji[entry.emoji] = entry.emoji;
  }

  return `/* This file is generated by scripts/generate-emojis.js */
(function (global) {
  const data = {
    emojis: ${JSON.stringify(list, null, 2)},
    positions: ${JSON.stringify(positions, null, 2)},
    aliasToEmoji: ${JSON.stringify(aliasToEmoji, null, 2)},
    literalToEmoji: ${JSON.stringify(literalToEmoji, null, 2)}
  };

  global.EmojiStackData = data;

  if (global.EmojiStack) {
    global.EmojiStack.data = data;
    global.EmojiStack.emojis = data.emojis;
  }
})(window);
`;
}

function generateEmojis() {
  writeFile("emojis.generated.css", generateEmojiCss(emojis));
  writeFile("aliases.generated.css", generateAliasCss(emojis));
  writeFile("registry.js", generateRegistry(emojis));
  return emojis;
}

if (require.main === module) {
  generateEmojis();
}

module.exports = generateEmojis;
