/* This file is generated by scripts/generate-emojis.js */
(function (global) {
  const data = {
    emojis: [
  {
    "emoji": "🍓",
    "alias": "strawberry",
    "label": "Strawberry",
    "category": "fruit"
  },
  {
    "emoji": "🍼",
    "alias": "bottle",
    "label": "Baby Bottle",
    "category": "drinks"
  },
  {
    "emoji": "🥛",
    "alias": "milk",
    "label": "Glass of Milk",
    "category": "drinks"
  },
  {
    "emoji": "☕",
    "alias": "coffee",
    "label": "Hot Coffee",
    "category": "drinks"
  },
  {
    "emoji": "💀",
    "alias": "skull",
    "label": "Skull",
    "category": "cursed"
  },
  {
    "emoji": "🔥",
    "alias": "fire",
    "label": "Fire",
    "category": "symbols"
  },
  {
    "emoji": "💻",
    "alias": "laptop",
    "label": "Laptop",
    "category": "tech"
  },
  {
    "emoji": "📦",
    "alias": "box",
    "label": "Package Box",
    "category": "storage"
  },
  {
    "emoji": "🍝",
    "alias": "spaghetti",
    "label": "Spaghetti",
    "category": "food"
  },
  {
    "emoji": "🗂️",
    "alias": "dividers",
    "label": "Card Dividers",
    "category": "office"
  },
  {
    "emoji": "😇",
    "alias": "angel",
    "label": "Smiling Face with Halo",
    "category": "creatures"
  },
  {
    "emoji": "🐱",
    "alias": "cat",
    "label": "Cat Face",
    "category": "creatures"
  },
  {
    "emoji": "🧠",
    "alias": "brain",
    "label": "Brain",
    "category": "cursed"
  },
  {
    "emoji": "🔋",
    "alias": "battery",
    "label": "Battery",
    "category": "tech"
  },
  {
    "emoji": "🍜",
    "alias": "ramen",
    "label": "Steaming Bowl",
    "category": "food"
  },
  {
    "emoji": "🌶️",
    "alias": "pepper",
    "label": "Hot Pepper",
    "category": "food"
  },
  {
    "emoji": "☣️",
    "alias": "biohazard",
    "label": "Biohazard",
    "category": "symbols"
  },
  {
    "emoji": "🧴",
    "alias": "lotion",
    "label": "Lotion Bottle",
    "category": "objects"
  },
  {
    "emoji": "🧃",
    "alias": "juice-box",
    "label": "Beverage Box",
    "category": "drinks"
  },
  {
    "emoji": "🫙",
    "alias": "jar",
    "label": "Jar",
    "category": "containers"
  },
  {
    "emoji": "📁",
    "alias": "folder",
    "label": "File Folder",
    "category": "office"
  },
  {
    "emoji": "💾",
    "alias": "floppy-disk",
    "label": "Floppy Disk",
    "category": "tech"
  },
  {
    "emoji": "🔌",
    "alias": "plug",
    "label": "Electric Plug",
    "category": "tech"
  },
  {
    "emoji": "📱",
    "alias": "phone",
    "label": "Mobile Phone",
    "category": "tech"
  },
  {
    "emoji": "🧪",
    "alias": "test-tube",
    "label": "Test Tube",
    "category": "objects"
  },
  {
    "emoji": "🍋",
    "alias": "lemon",
    "label": "Lemon",
    "category": "fruit"
  },
  {
    "emoji": "🍎",
    "alias": "apple",
    "label": "Red Apple",
    "category": "fruit"
  },
  {
    "emoji": "🍒",
    "alias": "cherries",
    "label": "Cherries",
    "category": "fruit"
  },
  {
    "emoji": "🍔",
    "alias": "burger",
    "label": "Hamburger",
    "category": "food"
  },
  {
    "emoji": "🍟",
    "alias": "fries",
    "label": "French Fries",
    "category": "food"
  },
  {
    "emoji": "🍕",
    "alias": "pizza",
    "label": "Pizza",
    "category": "food"
  },
  {
    "emoji": "🌮",
    "alias": "taco",
    "label": "Taco",
    "category": "food"
  },
  {
    "emoji": "🍣",
    "alias": "sushi",
    "label": "Sushi",
    "category": "food"
  },
  {
    "emoji": "🧋",
    "alias": "bubble-tea",
    "label": "Bubble Tea",
    "category": "drinks"
  },
  {
    "emoji": "🥤",
    "alias": "soda",
    "label": "Cup with Straw",
    "category": "drinks"
  },
  {
    "emoji": "🧊",
    "alias": "ice",
    "label": "Ice Cube",
    "category": "objects"
  },
  {
    "emoji": "❤️",
    "alias": "heart",
    "label": "Red Heart",
    "category": "symbols"
  },
  {
    "emoji": "⚠️",
    "alias": "warning",
    "label": "Warning",
    "category": "symbols"
  },
  {
    "emoji": "✨",
    "alias": "sparkles",
    "label": "Sparkles",
    "category": "symbols"
  },
  {
    "emoji": "💣",
    "alias": "bomb",
    "label": "Bomb",
    "category": "cursed"
  },
  {
    "emoji": "👁️",
    "alias": "eye",
    "label": "Eye",
    "category": "cursed"
  },
  {
    "emoji": "🦴",
    "alias": "bone",
    "label": "Bone",
    "category": "creatures"
  },
  {
    "emoji": "🐸",
    "alias": "frog",
    "label": "Frog",
    "category": "creatures"
  },
  {
    "emoji": "🐀",
    "alias": "rat",
    "label": "Rat",
    "category": "creatures"
  },
  {
    "emoji": "🐍",
    "alias": "snake",
    "label": "Snake",
    "category": "creatures"
  },
  {
    "emoji": "👑",
    "alias": "crown",
    "label": "Crown",
    "category": "objects"
  },
  {
    "emoji": "🔒",
    "alias": "lock",
    "label": "Locked",
    "category": "symbols"
  },
  {
    "emoji": "🔓",
    "alias": "unlock",
    "label": "Unlocked",
    "category": "symbols"
  },
  {
    "emoji": "📷",
    "alias": "camera",
    "label": "Camera",
    "category": "tech"
  },
  {
    "emoji": "🎧",
    "alias": "headphones",
    "label": "Headphones",
    "category": "tech"
  },
  {
    "emoji": "📚",
    "alias": "books",
    "label": "Books",
    "category": "office"
  },
  {
    "emoji": "🗃️",
    "alias": "card-box",
    "label": "Card File Box",
    "category": "storage"
  },
  {
    "emoji": "🪫",
    "alias": "battery-low",
    "label": "Low Battery",
    "category": "tech"
  },
  {
    "emoji": "🔦",
    "alias": "flashlight",
    "label": "Flashlight",
    "category": "objects"
  },
  {
    "emoji": "🧼",
    "alias": "soap",
    "label": "Soap",
    "category": "objects"
  },
  {
    "emoji": "🪵",
    "alias": "wood",
    "label": "Wood",
    "category": "objects"
  },
  {
    "emoji": "🛒",
    "alias": "cart",
    "label": "Shopping Cart",
    "category": "objects"
  },
  {
    "emoji": "🧺",
    "alias": "basket",
    "label": "Basket",
    "category": "containers"
  },
  {
    "emoji": "🪣",
    "alias": "bucket",
    "label": "Bucket",
    "category": "containers"
  },
  {
    "emoji": "🧰",
    "alias": "toolbox",
    "label": "Toolbox",
    "category": "objects"
  },
  {
    "emoji": "🧲",
    "alias": "magnet",
    "label": "Magnet",
    "category": "objects"
  },
  {
    "emoji": "🎮",
    "alias": "gamepad",
    "label": "Video Game",
    "category": "tech"
  },
  {
    "emoji": "📺",
    "alias": "tv",
    "label": "Television",
    "category": "tech"
  },
  {
    "emoji": "🖨️",
    "alias": "printer",
    "label": "Printer",
    "category": "tech"
  },
  {
    "emoji": "💿",
    "alias": "optical-disk",
    "label": "Optical Disk",
    "category": "tech"
  },
  {
    "emoji": "🧬",
    "alias": "dna",
    "label": "DNA",
    "category": "objects"
  },
  {
    "emoji": "👻",
    "alias": "ghost",
    "label": "Ghost",
    "category": "cursed"
  },
  {
    "emoji": "📂",
    "alias": "folder-open",
    "label": "Open Folder",
    "category": "office"
  },
  {
    "emoji": "🧾",
    "alias": "receipt",
    "label": "Receipt",
    "category": "office"
  },
  {
    "emoji": "📅",
    "alias": "calendar",
    "label": "Calendar",
    "category": "office"
  },
  {
    "emoji": "📝",
    "alias": "memo",
    "label": "Memo",
    "category": "office"
  },
  {
    "emoji": "📌",
    "alias": "pushpin",
    "label": "Pushpin",
    "category": "office"
  },
  {
    "emoji": "🔑",
    "alias": "key",
    "label": "Key",
    "category": "objects"
  },
  {
    "emoji": "🛡️",
    "alias": "shield",
    "label": "Shield",
    "category": "symbols"
  },
  {
    "emoji": "🛰️",
    "alias": "satellite",
    "label": "Satellite",
    "category": "tech"
  },
  {
    "emoji": "🤖",
    "alias": "robot",
    "label": "Robot",
    "category": "tech"
  },
  {
    "emoji": "👽",
    "alias": "alien",
    "label": "Alien",
    "category": "creatures"
  },
  {
    "emoji": "☁️",
    "alias": "cloud",
    "label": "Cloud",
    "category": "symbols"
  },
  {
    "emoji": "⚡",
    "alias": "lightning",
    "label": "Lightning",
    "category": "symbols"
  },
  {
    "emoji": "💧",
    "alias": "droplet",
    "label": "Droplet",
    "category": "symbols"
  },
  {
    "emoji": "💩",
    "alias": "poop",
    "label": "Pile of Poo",
    "category": "cursed"
  },
  {
    "emoji": "💊",
    "alias": "pill",
    "label": "Pill",
    "category": "objects"
  },
  {
    "emoji": "💉",
    "alias": "syringe",
    "label": "Syringe",
    "category": "objects"
  },
  {
    "emoji": "🔬",
    "alias": "microscope",
    "label": "Microscope",
    "category": "tech"
  },
  {
    "emoji": "🧫",
    "alias": "petri-dish",
    "label": "Petri Dish",
    "category": "objects"
  },
  {
    "emoji": "✂️",
    "alias": "scissors",
    "label": "Scissors",
    "category": "office"
  },
  {
    "emoji": "📎",
    "alias": "paperclip",
    "label": "Paperclip",
    "category": "office"
  },
  {
    "emoji": "📫",
    "alias": "mailbox",
    "label": "Mailbox",
    "category": "objects"
  },
  {
    "emoji": "🍪",
    "alias": "cookie",
    "label": "Cookie",
    "category": "food"
  },
  {
    "emoji": "🍩",
    "alias": "doughnut",
    "label": "Doughnut",
    "category": "food"
  },
  {
    "emoji": "🧀",
    "alias": "cheese",
    "label": "Cheese Wedge",
    "category": "food"
  },
  {
    "emoji": "🥚",
    "alias": "egg",
    "label": "Egg",
    "category": "food"
  },
  {
    "emoji": "🍄",
    "alias": "mushroom",
    "label": "Mushroom",
    "category": "food"
  },
  {
    "emoji": "🍌",
    "alias": "banana",
    "label": "Banana",
    "category": "fruit"
  },
  {
    "emoji": "🍐",
    "alias": "pear",
    "label": "Pear",
    "category": "fruit"
  },
  {
    "emoji": "🍉",
    "alias": "watermelon",
    "label": "Watermelon",
    "category": "fruit"
  },
  {
    "emoji": "🥑",
    "alias": "avocado",
    "label": "Avocado",
    "category": "food"
  },
  {
    "emoji": "🥕",
    "alias": "carrot",
    "label": "Carrot",
    "category": "food"
  },
  {
    "emoji": "🍵",
    "alias": "tea",
    "label": "Tea",
    "category": "drinks"
  },
  {
    "emoji": "🍺",
    "alias": "beer",
    "label": "Beer",
    "category": "drinks"
  },
  {
    "emoji": "🍷",
    "alias": "wine",
    "label": "Wine",
    "category": "drinks"
  },
  {
    "emoji": "🏅",
    "alias": "medal",
    "label": "Medal",
    "category": "symbols"
  },
  {
    "emoji": "⭐",
    "alias": "star",
    "label": "Star",
    "category": "symbols"
  },
  {
    "emoji": "🌙",
    "alias": "moon",
    "label": "Moon",
    "category": "symbols"
  },
  {
    "emoji": "☀️",
    "alias": "sun",
    "label": "Sun",
    "category": "symbols"
  },
  {
    "emoji": "⏳",
    "alias": "hourglass",
    "label": "Hourglass",
    "category": "objects"
  }
],
    positions: [
  {
    "id": "s-center",
    "label": "Direct Center",
    "x": 0,
    "y": 0,
    "kind": "direct"
  },
  {
    "id": "s-tl",
    "label": "Top Left",
    "x": -0.34,
    "y": -0.34,
    "kind": "macro"
  },
  {
    "id": "s-tc",
    "label": "Top Center",
    "x": 0,
    "y": -0.34,
    "kind": "macro"
  },
  {
    "id": "s-tr",
    "label": "Top Right",
    "x": 0.34,
    "y": -0.34,
    "kind": "macro"
  },
  {
    "id": "s-ml",
    "label": "Middle Left",
    "x": -0.34,
    "y": 0,
    "kind": "macro"
  },
  {
    "id": "s-mc",
    "label": "Middle Center",
    "x": 0,
    "y": 0,
    "kind": "macro"
  },
  {
    "id": "s-mr",
    "label": "Middle Right",
    "x": 0.34,
    "y": 0,
    "kind": "macro"
  },
  {
    "id": "s-bl",
    "label": "Bottom Left",
    "x": -0.34,
    "y": 0.34,
    "kind": "macro"
  },
  {
    "id": "s-bc",
    "label": "Bottom Center",
    "x": 0,
    "y": 0.34,
    "kind": "macro"
  },
  {
    "id": "s-br",
    "label": "Bottom Right",
    "x": 0.34,
    "y": 0.34,
    "kind": "macro"
  },
  {
    "id": "s-tl-nw",
    "label": "Top Left NW",
    "x": -0.45,
    "y": -0.45,
    "kind": "micro"
  },
  {
    "id": "s-tl-ne",
    "label": "Top Left NE",
    "x": -0.23,
    "y": -0.45,
    "kind": "micro"
  },
  {
    "id": "s-tl-sw",
    "label": "Top Left SW",
    "x": -0.45,
    "y": -0.23,
    "kind": "micro"
  },
  {
    "id": "s-tl-se",
    "label": "Top Left SE",
    "x": -0.23,
    "y": -0.23,
    "kind": "micro"
  },
  {
    "id": "s-tc-nw",
    "label": "Top Center NW",
    "x": -0.11,
    "y": -0.45,
    "kind": "micro"
  },
  {
    "id": "s-tc-ne",
    "label": "Top Center NE",
    "x": 0.11,
    "y": -0.45,
    "kind": "micro"
  },
  {
    "id": "s-tc-sw",
    "label": "Top Center SW",
    "x": -0.11,
    "y": -0.23,
    "kind": "micro"
  },
  {
    "id": "s-tc-se",
    "label": "Top Center SE",
    "x": 0.11,
    "y": -0.23,
    "kind": "micro"
  },
  {
    "id": "s-tr-nw",
    "label": "Top Right NW",
    "x": 0.23,
    "y": -0.45,
    "kind": "micro"
  },
  {
    "id": "s-tr-ne",
    "label": "Top Right NE",
    "x": 0.45,
    "y": -0.45,
    "kind": "micro"
  },
  {
    "id": "s-tr-sw",
    "label": "Top Right SW",
    "x": 0.23,
    "y": -0.23,
    "kind": "micro"
  },
  {
    "id": "s-tr-se",
    "label": "Top Right SE",
    "x": 0.45,
    "y": -0.23,
    "kind": "micro"
  },
  {
    "id": "s-ml-nw",
    "label": "Middle Left NW",
    "x": -0.45,
    "y": -0.11,
    "kind": "micro"
  },
  {
    "id": "s-ml-ne",
    "label": "Middle Left NE",
    "x": -0.23,
    "y": -0.11,
    "kind": "micro"
  },
  {
    "id": "s-ml-sw",
    "label": "Middle Left SW",
    "x": -0.45,
    "y": 0.11,
    "kind": "micro"
  },
  {
    "id": "s-ml-se",
    "label": "Middle Left SE",
    "x": -0.23,
    "y": 0.11,
    "kind": "micro"
  },
  {
    "id": "s-mc-nw",
    "label": "Middle Center NW",
    "x": -0.11,
    "y": -0.11,
    "kind": "micro"
  },
  {
    "id": "s-mc-ne",
    "label": "Middle Center NE",
    "x": 0.11,
    "y": -0.11,
    "kind": "micro"
  },
  {
    "id": "s-mc-sw",
    "label": "Middle Center SW",
    "x": -0.11,
    "y": 0.11,
    "kind": "micro"
  },
  {
    "id": "s-mc-se",
    "label": "Middle Center SE",
    "x": 0.11,
    "y": 0.11,
    "kind": "micro"
  },
  {
    "id": "s-mr-nw",
    "label": "Middle Right NW",
    "x": 0.23,
    "y": -0.11,
    "kind": "micro"
  },
  {
    "id": "s-mr-ne",
    "label": "Middle Right NE",
    "x": 0.45,
    "y": -0.11,
    "kind": "micro"
  },
  {
    "id": "s-mr-sw",
    "label": "Middle Right SW",
    "x": 0.23,
    "y": 0.11,
    "kind": "micro"
  },
  {
    "id": "s-mr-se",
    "label": "Middle Right SE",
    "x": 0.45,
    "y": 0.11,
    "kind": "micro"
  },
  {
    "id": "s-bl-nw",
    "label": "Bottom Left NW",
    "x": -0.45,
    "y": 0.23,
    "kind": "micro"
  },
  {
    "id": "s-bl-ne",
    "label": "Bottom Left NE",
    "x": -0.23,
    "y": 0.23,
    "kind": "micro"
  },
  {
    "id": "s-bl-sw",
    "label": "Bottom Left SW",
    "x": -0.45,
    "y": 0.45,
    "kind": "micro"
  },
  {
    "id": "s-bl-se",
    "label": "Bottom Left SE",
    "x": -0.23,
    "y": 0.45,
    "kind": "micro"
  },
  {
    "id": "s-bc-nw",
    "label": "Bottom Center NW",
    "x": -0.11,
    "y": 0.23,
    "kind": "micro"
  },
  {
    "id": "s-bc-ne",
    "label": "Bottom Center NE",
    "x": 0.11,
    "y": 0.23,
    "kind": "micro"
  },
  {
    "id": "s-bc-sw",
    "label": "Bottom Center SW",
    "x": -0.11,
    "y": 0.45,
    "kind": "micro"
  },
  {
    "id": "s-bc-se",
    "label": "Bottom Center SE",
    "x": 0.11,
    "y": 0.45,
    "kind": "micro"
  },
  {
    "id": "s-br-nw",
    "label": "Bottom Right NW",
    "x": 0.23,
    "y": 0.23,
    "kind": "micro"
  },
  {
    "id": "s-br-ne",
    "label": "Bottom Right NE",
    "x": 0.45,
    "y": 0.23,
    "kind": "micro"
  },
  {
    "id": "s-br-sw",
    "label": "Bottom Right SW",
    "x": 0.23,
    "y": 0.45,
    "kind": "micro"
  },
  {
    "id": "s-br-se",
    "label": "Bottom Right SE",
    "x": 0.45,
    "y": 0.45,
    "kind": "micro"
  }
],
    aliasToEmoji: {
  "e-strawberry": "🍓",
  "e-bottle": "🍼",
  "e-milk": "🥛",
  "e-coffee": "☕",
  "e-skull": "💀",
  "e-fire": "🔥",
  "e-laptop": "💻",
  "e-box": "📦",
  "e-spaghetti": "🍝",
  "e-dividers": "🗂️",
  "e-angel": "😇",
  "e-cat": "🐱",
  "e-brain": "🧠",
  "e-battery": "🔋",
  "e-ramen": "🍜",
  "e-pepper": "🌶️",
  "e-biohazard": "☣️",
  "e-lotion": "🧴",
  "e-juice-box": "🧃",
  "e-jar": "🫙",
  "e-folder": "📁",
  "e-floppy-disk": "💾",
  "e-plug": "🔌",
  "e-phone": "📱",
  "e-test-tube": "🧪",
  "e-lemon": "🍋",
  "e-apple": "🍎",
  "e-cherries": "🍒",
  "e-burger": "🍔",
  "e-fries": "🍟",
  "e-pizza": "🍕",
  "e-taco": "🌮",
  "e-sushi": "🍣",
  "e-bubble-tea": "🧋",
  "e-soda": "🥤",
  "e-ice": "🧊",
  "e-heart": "❤️",
  "e-warning": "⚠️",
  "e-sparkles": "✨",
  "e-bomb": "💣",
  "e-eye": "👁️",
  "e-bone": "🦴",
  "e-frog": "🐸",
  "e-rat": "🐀",
  "e-snake": "🐍",
  "e-crown": "👑",
  "e-lock": "🔒",
  "e-unlock": "🔓",
  "e-camera": "📷",
  "e-headphones": "🎧",
  "e-books": "📚",
  "e-card-box": "🗃️",
  "e-battery-low": "🪫",
  "e-flashlight": "🔦",
  "e-soap": "🧼",
  "e-wood": "🪵",
  "e-cart": "🛒",
  "e-basket": "🧺",
  "e-bucket": "🪣",
  "e-toolbox": "🧰",
  "e-magnet": "🧲",
  "e-gamepad": "🎮",
  "e-tv": "📺",
  "e-printer": "🖨️",
  "e-optical-disk": "💿",
  "e-dna": "🧬",
  "e-ghost": "👻",
  "e-folder-open": "📂",
  "e-receipt": "🧾",
  "e-calendar": "📅",
  "e-memo": "📝",
  "e-pushpin": "📌",
  "e-key": "🔑",
  "e-shield": "🛡️",
  "e-satellite": "🛰️",
  "e-robot": "🤖",
  "e-alien": "👽",
  "e-cloud": "☁️",
  "e-lightning": "⚡",
  "e-droplet": "💧",
  "e-poop": "💩",
  "e-pill": "💊",
  "e-syringe": "💉",
  "e-microscope": "🔬",
  "e-petri-dish": "🧫",
  "e-scissors": "✂️",
  "e-paperclip": "📎",
  "e-mailbox": "📫",
  "e-cookie": "🍪",
  "e-doughnut": "🍩",
  "e-cheese": "🧀",
  "e-egg": "🥚",
  "e-mushroom": "🍄",
  "e-banana": "🍌",
  "e-pear": "🍐",
  "e-watermelon": "🍉",
  "e-avocado": "🥑",
  "e-carrot": "🥕",
  "e-tea": "🍵",
  "e-beer": "🍺",
  "e-wine": "🍷",
  "e-medal": "🏅",
  "e-star": "⭐",
  "e-moon": "🌙",
  "e-sun": "☀️",
  "e-hourglass": "⏳"
},
    literalToEmoji: {
  "🍓": "🍓",
  "🍼": "🍼",
  "🥛": "🥛",
  "☕": "☕",
  "💀": "💀",
  "🔥": "🔥",
  "💻": "💻",
  "📦": "📦",
  "🍝": "🍝",
  "🗂️": "🗂️",
  "😇": "😇",
  "🐱": "🐱",
  "🧠": "🧠",
  "🔋": "🔋",
  "🍜": "🍜",
  "🌶️": "🌶️",
  "☣️": "☣️",
  "🧴": "🧴",
  "🧃": "🧃",
  "🫙": "🫙",
  "📁": "📁",
  "💾": "💾",
  "🔌": "🔌",
  "📱": "📱",
  "🧪": "🧪",
  "🍋": "🍋",
  "🍎": "🍎",
  "🍒": "🍒",
  "🍔": "🍔",
  "🍟": "🍟",
  "🍕": "🍕",
  "🌮": "🌮",
  "🍣": "🍣",
  "🧋": "🧋",
  "🥤": "🥤",
  "🧊": "🧊",
  "❤️": "❤️",
  "⚠️": "⚠️",
  "✨": "✨",
  "💣": "💣",
  "👁️": "👁️",
  "🦴": "🦴",
  "🐸": "🐸",
  "🐀": "🐀",
  "🐍": "🐍",
  "👑": "👑",
  "🔒": "🔒",
  "🔓": "🔓",
  "📷": "📷",
  "🎧": "🎧",
  "📚": "📚",
  "🗃️": "🗃️",
  "🪫": "🪫",
  "🔦": "🔦",
  "🧼": "🧼",
  "🪵": "🪵",
  "🛒": "🛒",
  "🧺": "🧺",
  "🪣": "🪣",
  "🧰": "🧰",
  "🧲": "🧲",
  "🎮": "🎮",
  "📺": "📺",
  "🖨️": "🖨️",
  "💿": "💿",
  "🧬": "🧬",
  "👻": "👻",
  "📂": "📂",
  "🧾": "🧾",
  "📅": "📅",
  "📝": "📝",
  "📌": "📌",
  "🔑": "🔑",
  "🛡️": "🛡️",
  "🛰️": "🛰️",
  "🤖": "🤖",
  "👽": "👽",
  "☁️": "☁️",
  "⚡": "⚡",
  "💧": "💧",
  "💩": "💩",
  "💊": "💊",
  "💉": "💉",
  "🔬": "🔬",
  "🧫": "🧫",
  "✂️": "✂️",
  "📎": "📎",
  "📫": "📫",
  "🍪": "🍪",
  "🍩": "🍩",
  "🧀": "🧀",
  "🥚": "🥚",
  "🍄": "🍄",
  "🍌": "🍌",
  "🍐": "🍐",
  "🍉": "🍉",
  "🥑": "🥑",
  "🥕": "🥕",
  "🍵": "🍵",
  "🍺": "🍺",
  "🍷": "🍷",
  "🏅": "🏅",
  "⭐": "⭐",
  "🌙": "🌙",
  "☀️": "☀️",
  "⏳": "⏳"
}
  };

  global.EmojiStackData = data;

  if (global.EmojiStack) {
    global.EmojiStack.data = data;
    global.EmojiStack.emojis = data.emojis;
  }
})(window);
